

//tab
export const kTabNumUP  ="kTabNumUP";

//root
export const INITIALIZED = 'kreu.app.INITIALIZED';
export const ROOT_CHANGED = 'kreu.app.ROOT_CHANGED';


//
export const PRODUCT_FETCH = "PRODUCT_FETCH";
export const PRODUCT_RECEIVE ="PRODUCT_RECEIVE";

//PRODUCT TRANG CHU
export const PRODUCT_HOMEPAGE_FETCH = "PRODUCT_HOMEPAGE_FETCH";
export const PRODUCT_HOMEPAGE_RECEIVE ="PRODUCT_HOMEPAGE_RECEIVE";

export const PRODUCT_SPCT_FETCH = "PRODUCT_SPCT_FETCH";
export const PRODUCT_SPCT_RECEIVE = "PRODUCT_SPCT_RECEIVE";


export const PRODUCT_FILTER_SET = "PRODUCT_FILTER_SET";
//
export const DMSP_FETCH = "DMSP_FETCH";
export const DMSP_RECEIVE ="DMSP_RECEIVE";

//nofification
export const NOTI_UP="NOTI_UP";
export const NOTI_DOWN="NOTI_DOWN";
export const NOTI_SET_EQUAL="NOTI_SET_EQUAL";


//cart
export const CART_ADD = "CART_ADD";
export const CART_CLEAR="CART_CLEAR";
export const CART_REMOVE_ITEM="CART_REMOVE_ITEM";

export const CART_SET_SOLUONG="CART_SET_SOLUONG";


//AUTH
export const AUTH_LOGIN_FETCH = "AUTH_LOGIN_FETCH";
export const AUTH_LOGIN_RECEIVE = "AUTH_LOGIN_RECEIVE";

export const AUTH_REGISTER_FETCH = "AUTH_REGISTER_FETCH";
export const AUTH_REGISTER_RECEIVE = "AUTH_REGISTER_RECEIVE";

export const AUTH_LOGOUT="AUTH_LOGOUT";
export const AUTH_LOGIN_SAVE="AUTH_LOGIN_SAVE";

//product km
export const PRODUCT_KHUYENMAI_FETCH = "PRODUCT_KHUYENMAI_FETCH";
export const PRODUCT_KHUYENMAI_RECEIVE ="PRODUCT_KHUYENMAI_RECEIVE";

//don hang
export const DONHANG_FETCH = "DONHANG_FETCH";
export const DONHANG_RECEIVE ="DONHANG_RECEIVE";


export const LOGOUT_DONHANG = "LOGOUT_DONHANG";
export const LOGOUT_GIOHANG ="LOGOUT_GIOHANG";



//tich diem
export const DONHANG_TICHDIEM_FETCH = "DONHANG_TICHDIEM_FETCH";
export const DONHANG_TICHDIEM_RECEIVE ="DONHANG_TICHDIEM_RECEIVE";
//dat hang

//
export const POST_DATHANG_FETCH = "POST_DATHANG_FETCH";
export const POST_DATHANG_RECEIVE ="POST_DATHANG_RECEIVE";

//ARTICLE
export const ARTICLE_FETCH = "ARTICLE_FETCH";
export const ARTICLER_RECEIVE ="ARTICLER_RECEIVE";
export const ARTICLE_DETAIL_RECEIVE ="ARTICLE_DETAIL_RECEIVE";

//doi mat khau
export const AUTH_DOIMATKHAU_RECEIVE="AUTH_DOIMATKHAU_RECEIVE";

//cap nhat tai khoan
export const AUTH_CAPNHATTAIKHOAN_RECEIVE="AUTH_CAPNHATTAIKHOAN_RECEIVE";